name: "Energy Smart Bridge"
description: "Energy Smart Bridge"
version: "1.0.0"
slug: "energy_smart_bridge"
image: "ghcr.io/starsoccer/energysmartbridge/{arch}"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  443/tcp: 443
options:
  MQTT_PORT: 1883
  MQTT_SERVER: null
  MQTT_USERNAME: null
  MQTT_PASSWORD: null
  log_level: list(fatal|error|warn|info|debug|trace)
schema:
  MQTT_PORT: port
  MQTT_SERVER: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  log_level: list(fatal|error|warn|info|debug|trace)